AGENT_ZERO = 'agent_0'
AGENT_ONE = 'agent_1'
AGENT_TWO = 'agent_2'

STATES = 'states'
NEXT_STATES = 'next_states'
REWARDS = 'rewards'
ACTIONS = 'actions'
Q_TOTALS = 'q_totals'
Q_VALS = 'q_values'

AGENT_WEIGHT_NAME = 'agent_nn_weight'
MIX_WEIGHT_NAME = 'mix_nn_weight'
REWARD_FILENAME = 'reward.txt'
LOSS_FILENAME = 'loss.txt'
